version: '3'
services:
  shopme-backend:
    build:
      context: ./
      dockerfile:  Dockerfile.backend
    ports:
      - "8080:8080"
  shopme-frontend:
    build:
      context: ./
      dockerfile:  Dockerfile.frontend
    ports:
      - "80:80" 