# --------------------- Start the Server ----------------------------#
FROM maven:3.8.2-jdk-8

WORKDIR /usr/app/Shopme
COPY ./ ./
WORKDIR /usr/app/Shopme/ShopmeWebParent/ShopmeFrontEnd

COPY ./ShopmeWebParent/ShopmeFrontEnd/target/*.jar frontend-app.jar
CMD ["java","-jar","./frontend-app.jar"]